[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
license = {text = "Apache-2.0"}  # SPDX-идентификатор
classifiers = [
    "License :: OSI Approved :: Apache Software License"  # OSI Approved
]
